version: 2

models:

    - name: sales
      description: This is the model name 
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: is only INTEGER 

            tests : 
            - not_null 

          - name: products_id
            description: it is the primary key

            tests : 
            - not_null

          - name: qty

          - name: turnover
            description: it is the totall incomes 

            tests : 
            - not_null

          - name: purchase_cost
            description: the NET of incomes 

            tests : 
            - not_null

          - name: margin
            description: The NET of turnover between < 0 >
